artifacts_root : artifacts

data_ingestion:
  root_folder: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_folder: artifacts/data_validation
  status_file_path: artifacts/data_validation/status.txt
  required_file: [train,validation,test , dataset_dict.json]

data_transformation:
  root_folder: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


data_training:
  root_folder: artifacts/data_training
  train_data_path: artifacts/data_transformation/samsum_dataset
  model_ckeckpoint: google/pegasus-cnn_dailymail
  

model_evaluation:
  root_folder: artifacts/model_evaluation
  model_path: artifacts/data_training/trained_model
  tokenizer_path: artifacts/data_training/trained_tokenizer
  test_data_path: artifacts/data_transformation/samsum_dataset
  evaluations_result: artifacts/model_evaluation/metrics.csv